POS_SIZE = 50
ENTITY_SIZE = 19
BATCH_SIZE = 32
NUM_FEATURES = 4

RNN_DROPOUT_RATE = 0.4
EMBEDDING_DROPOUT_RATE = 0.4
EMBEDDING_SIZE = 300
HIDDEN_SIZE = 128
WORDS_IN_VOCABULARY = 91187

#QUEB_SIZE = HIDDEN_SIZE
#INPUT_CONTEXT_LEN = EMBEDDING_SIZE + NUM_FEATURES + QUEB_SIZE + POS_SIZE + ENTITY_SIZE
INPUT_CONTEXT_LEN = EMBEDDING_SIZE + NUM_FEATURES + POS_SIZE + ENTITY_SIZE
INPUT_QUESTION_LEN = EMBEDDING_SIZE

TRAIN_CONTEXT_PATH = 'TRAIN_CONTEXTS'
TRAIN_QUESTION_PATH = 'TRAIN_QUESTIONS'
DEV_CONTEXT_PATH = 'DEV_CONTEXTS'
DEV_QUESTION_PATH = 'DEV_QUESTIONS'
TRAIN_ANSWER_BIN_PATH = 'TRAIN_ANSW_BIN'
TRAIN_ANSWER_PAIRS_PATH = 'TRAIN_ANSW_PAIRS'
DO_PADDING = True
